services:
  automation:
    image: ciuse99/suggestarr:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY} # (Optional: You can configure it in the dashboard)
      JELLYFIN_API_URL: ${JELLYFIN_API_URL} # (Optional: You can configure it in the dashboard)
      JELLYFIN_TOKEN: ${JELLYFIN_TOKEN} # (Optional: You can configure it in the dashboard)
      JELLYSEER_API_URL: ${JELLYSEER_API_URL} # (Optional: You can configure it in the dashboard)
      JELLYSEER_TOKEN: ${JELLYSEER_TOKEN} # (Optional: You can configure it in the dashboard)
      MAX_SIMILAR_MOVIE: 5 # (Optional: You can configure it in the dashboard. Default: 2, Max: 20)
      MAX_SIMILAR_TV: 2 # (Optional: You can configure it in the dashboard. Default: 2, Max: 20)
      CRON_TIMES: ${CRON_TIMES:-0 0 * * *}  # (Optional: You can configure it in the dashboard. Default run at midnight.)
    volumes:
      - .:/app
    container_name: SuggestArr
    restart: always
    ports:
      - "5000:5000"
