version: "3.8"

services:
  automation:
    image: ciuse99/jellyseer_request_automation:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
      JELLYFIN_API_URL: ${JELLYFIN_API_URL}
      JELLYFIN_TOKEN: ${JELLYFIN_TOKEN}
      JELLYSEER_API_URL: ${JELLYSEER_API_URL}
      JELLYSEER_TOKEN: ${JELLYSEER_TOKEN}
      MAX_SIMILAR_MOVIE: 5 # (Optional: default 5, max 20)
      MAX_SIMILAR_TV: 2 # (Optional: default 2, max 20)
    volumes:
      - .:/app
    container_name: jellyser_automation_job
    restart: always
