
name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ciuse99 --password-stdin

      - name: Build Docker Image
        run: |
          docker build . -t ciuse99/suggestarr:latest
      - name: Push Docker Image
        run: |
          docker push ciuse99/suggestarr:latest
          
      # temporary keeping two images
      - name: Build Docker Image
        run: |
          docker build . -t ciuse99/jellyseer_request_automation:latest
      - name: Push Docker Image
        run: |
          docker push ciuse99/jellyseer_request_automation:latest