name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u giuseppe99barchetta --password-stdin

      - name: Build Docker Image
        run: |
          docker build . -t ghcr.io/giuseppe99barchetta/suggestarr:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/giuseppe99barchetta/suggestarr:latest
