
name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - nightly
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ciuse99 --password-stdin

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ciuse99/suggestarr:nightly --push .
      - name: Push Docker Image
        run: |
          docker push ciuse99/suggestarr:nightly
